---
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package_version: "19.03.2-3.el7"
docker_package: "docker-{{ docker_edition }}-{{ docker_package_version }}"
docker_package_state: present

docker_cli_package: "docker-{{ docker_edition }}-cli-{{ docker_package_version }}"
docker_cli_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: yes
docker_restart_handler_state: restarted

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.24.1"
docker_compose_path: /usr/local/bin/docker-compose
docker_compose_checksum: "sha256:cfb3439956216b1248308141f7193776fcf4b9c9b49cbbe2fb07885678e2bb8a"

# Used only for RedHat/CentOS/Fedora.
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo

# A list of users who will be added to the docker group.
docker_users: []