---
# file: tasks/config.yml
- name: set user.name
  git_config:
    name: user.name
    scope: global
    value: "{{ user_name }}"

- name: set user.email
  git_config:
    name: user.email
    scope: global
    value: "{{ user_email }}"