---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install docker
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Install docker-cli
  package:
    name: "{{ docker_cli_package }}"
    state: "{{ docker_cli_package_state }}"

- name: Install containerd.io
  package:
    name: "containerd.io"
    state: "present"

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0