---
# file: tasks/main.yml
- name: include setup-redhat.yml
  include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: install docker
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: install docker-cli
  package:
    name: "{{ docker_cli_package }}"
    state: "{{ docker_cli_package_state }}"

- name: install containerd.io
  package:
    name: "containerd.io"
    state: "present"

- name: ensure docker is started and enabled at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: include docker-compose.yml
  include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- name: include docker-users.yml
  include_tasks: docker-users.yml
  when: docker_users | length > 0