---
# file: tasks/setup-redhat.yml
- name: ensure old versions of docker are not installed
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: add docker gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: add docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: install required packages
  package:
    name:
#      - yum-utils
      - device-mapper-persistent-data
      - lvm2